import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { getCurrentWindow } from '@tauri-apps/api/window'
import { AtSign, ChevronRight, ContactRound, KeyRound, LockKeyhole, LogOut, Mail, MessageCircleMore, Minus, Phone, Plus, Search, ShieldCheck, Square, Trash2, Unlock, UserRound, X } from 'lucide-react'
import { Button } from './components/ui/button'

type AuthState = { authenticated: boolean; username: string | null; needs_registration: boolean }
type Vault = { vault_id: string; label: string }
type ContactInput = { kind: string; value: string; label: string; is_primary: boolean }
type Contact = ContactInput & { contact_id: string }
type PersonInput = { name: string; gender: string; birthday: string; note: string; contacts: ContactInput[] }
type PersonSummary = { person_id: string; name: string; gender: string; contact_count: number }
type Person = PersonSummary & { birthday: string | null; note: string | null; contacts: Contact[] }
type Credential = { credential_id: string; title: string; username: string | null; url: string | null }

function App() {
  const [auth, setAuth] = useState<AuthState | null>(null); const [vaults, setVaults] = useState<Vault[]>([]); const [vault, setVault] = useState<string | null>(null); const [unlocking, setUnlocking] = useState<string | null>(null); const [masterPassword, setMasterPassword] = useState(''); const [createVaultOpen, setCreateVaultOpen] = useState(false)
  const [section, setSection] = useState<'people' | 'credentials'>('people'); const [query, setQuery] = useState(''); const [people, setPeople] = useState<PersonSummary[]>([]); const [selected, setSelected] = useState<Person | null>(null); const [personEditor, setPersonEditor] = useState<Person | null>(null); const [credentials, setCredentials] = useState<Credential[]>([]); const [notice, setNotice] = useState<string | null>(null)
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 3000) }
  const loadVaults = () => invoke<Vault[]>('list_vaults').then(setVaults).catch(e => notify(String(e)))
  const loadPeople = (value = query) => invoke<PersonSummary[]>('list_people', { query: value }).then(setPeople).catch(e => notify(String(e)))
  const loadCredentials = (value = query) => invoke<Credential[]>('list_credentials', { query: value }).then(setCredentials).catch(e => notify(String(e)))
  useEffect(() => { invoke<AuthState>('auth_state').then(setAuth).catch(e => notify(String(e))) }, [])
  useEffect(() => { if (auth?.authenticated) loadVaults() }, [auth?.authenticated])
  useEffect(() => { if (!vault) return; if (section === 'people') loadPeople(); else loadCredentials() }, [query, section, vault])
  const unlock = async (e: FormEvent) => { e.preventDefault(); if (!unlocking) return; try { await invoke('unlock_vault', { vaultId: unlocking, masterPassword }); setVault(unlocking); setUnlocking(null); setMasterPassword(''); setSection('people'); notify('Vault 已解锁：联系人数据仅存在于内存 SQLite 中。') } catch (err) { notify(String(err)) } }
  const openPerson = async (id: string) => { try { setSelected(await invoke<Person>('get_person', { personId: id })) } catch (err) { notify(String(err)) } }
  const savePerson = async (input: PersonInput, id?: string) => { try { if (id) await invoke('update_person', { personId: id, input }); else await invoke('create_person', { input }); setPersonEditor(null); await loadPeople(); if (id) await openPerson(id); else setSelected(null); notify(id ? '联系人已更新。' : '联系人已加密保存。') } catch (err) { notify(String(err)) } }
  const deletePerson = async (id: string) => { if (!window.confirm('删除该联系人及其联系方式？')) return; try { await invoke('delete_person', { personId: id }); setSelected(null); loadPeople(); notify('联系人已删除。') } catch (err) { notify(String(err)) } }
  const lock = async () => { await invoke('lock_vault'); setVault(null); setPeople([]); setSelected(null); notify('Vault 已锁定。') }
  if (!auth?.authenticated) return <AuthScreen needsRegistration={auth?.needs_registration ?? false} onSuccess={setAuth} notify={notify}/>
  return <main className="h-screen min-h-[420px] overflow-hidden bg-[var(--ink)] text-white"><TitleBar/><div className="mx-auto flex h-[calc(100%-40px)] max-w-[1500px] bg-[radial-gradient(circle_at_72%_0%,rgba(58,104,93,0.2),transparent_38%),#111916]">
    <aside className="flex h-full min-h-0 w-[258px] shrink-0 flex-col overflow-y-auto border-r border-white/[0.07] bg-black/10 px-5 py-6"><Brand/><div className="mb-3 flex items-center justify-between px-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[var(--muted)]"><span>Vaults</span><button onClick={() => setCreateVaultOpen(true)} className="grid size-7 place-items-center rounded-md border border-[var(--mint)]/35 bg-[var(--mint)]/10 text-[var(--mint)] transition hover:scale-110 hover:bg-[var(--mint)] hover:text-[var(--ink)]" aria-label="创建 vault"><Plus size={16}/></button></div><nav className="space-y-1">{vaults.map(v => <button key={v.vault_id} onClick={() => vault === v.vault_id ? undefined : setUnlocking(v.vault_id)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-3 text-left text-sm transition hover:scale-[1.015] ${vault === v.vault_id ? 'bg-white/[0.09] text-white' : 'text-[var(--muted)] hover:bg-white/[0.06] hover:text-white'}`}><LockKeyhole size={15} className={vault === v.vault_id ? 'text-[var(--mint)]' : ''}/>{v.label}</button>)}</nav>{vault && <><hr className="my-7 border-white/[0.08]"/><p className="mb-2 px-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[var(--muted)]">Workspace</p><nav className="space-y-1"><Nav icon={<ContactRound size={17}/>} active={section==='people'} onClick={() => { setSection('people'); setQuery('') }}>People</Nav><Nav icon={<KeyRound size={17}/>} active={section==='credentials'} onClick={() => { setSection('credentials'); setQuery('') }}>Credentials</Nav><Nav icon={<MessageCircleMore size={17}/>} active={false} disabled>Activity · next</Nav></nav></>}<div className="sticky bottom-0 mt-auto bg-[#111916] pt-5"><div className="mb-3 rounded-xl border border-white/[0.08] bg-white/[0.035] p-3 text-xs text-[var(--muted)]"><UserRound size={14} className="mr-2 inline text-[var(--mint)]"/>{auth.username}</div>{vault && <Button variant="outline" className="mb-2 w-full" onClick={lock}><LockKeyhole size={16}/>Lock vault</Button>}<Button variant="quiet" className="w-full justify-start" onClick={() => { invoke('lock_vault').catch(() => undefined); setAuth({authenticated:false,username:null,needs_registration:false}); setVault(null) }}><LogOut size={16}/>Sign out</Button></div></aside>
    <section className="min-w-0 flex-1 overflow-y-auto px-6 py-8 lg:px-12"><header className="mb-7"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--mint)]">{vault ? `Vault / ${vault}` : 'Vault workspace'}</p><h1 className="mt-2 font-display text-3xl font-semibold">{vault ? section === 'people' ? 'People, not just passwords.' : 'Credentials.' : 'Choose or create a vault.'}</h1><p className="mt-2 text-sm text-[var(--muted)]">{vault ? '联系人、联系方式与关系数据可在解锁后的内存数据库中联表查询。' : '解锁后开始管理你的私密信息。'}</p></header>{!vault ? <EmptyVault onCreate={() => setCreateVaultOpen(true)}/> : section === 'people' ? <PeopleWorkspace people={people} selected={selected} query={query} setQuery={setQuery} onAdd={() => setPersonEditor({ person_id:'',name:'',gender:'',contact_count:0,birthday:'',note:'',contacts:[] })} onOpen={openPerson} onEdit={() => selected && setPersonEditor(selected)} onDelete={() => selected && deletePerson(selected.person_id)}/> : <CredentialsWorkspace credentials={credentials} query={query} setQuery={setQuery}/>}</section>
  </div>{unlocking && <UnlockDialog vault={unlocking} password={masterPassword} setPassword={setMasterPassword} onCancel={() => setUnlocking(null)} onSubmit={unlock}/>} {createVaultOpen && <CreateVaultDialog onCancel={() => setCreateVaultOpen(false)} onCreated={id => { setCreateVaultOpen(false); loadVaults(); setUnlocking(id) }} notify={notify}/>} {personEditor && <PersonDialog person={personEditor} onCancel={() => setPersonEditor(null)} onSave={savePerson}/>} {notice && <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-[var(--mint)]/20 bg-[#1b2d27] px-4 py-3 text-sm shadow-2xl">{notice}</div>}</main>
}
function TitleBar() { const windowHandle=getCurrentWindow(); return <header className="flex h-10 select-none border-b border-white/[0.08] bg-[#111916]" aria-label="应用标题栏"><div className="flex flex-1 items-center gap-2 px-4 text-[11px] font-bold tracking-[0.16em] text-[var(--muted)]" onMouseDown={event=>{if(event.button===0)void windowHandle.startDragging()}} onDoubleClick={()=>void windowHandle.toggleMaximize()}><span className="grid size-4 place-items-center rounded bg-[var(--mint)] text-[8px] text-[var(--ink)]">P</span>PASSMANAGER</div><div className="flex"><button type="button" onClick={()=>void windowHandle.minimize()} className="grid w-11 place-items-center text-[var(--muted)] transition hover:bg-white/[0.08] hover:text-white" aria-label="最小化"><Minus size={17}/></button><button type="button" onClick={()=>void windowHandle.toggleMaximize()} className="grid w-11 place-items-center text-[var(--muted)] transition hover:bg-white/[0.08] hover:text-white" aria-label="最大化或还原"><Square size={13}/></button><button type="button" onClick={()=>void windowHandle.close()} className="grid w-11 place-items-center text-[var(--muted)] transition hover:bg-red-500 hover:text-white" aria-label="关闭"><X size={16}/></button></div></header> }
function Brand() { return <div className="mb-10 flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-xl bg-[var(--mint)] text-[var(--ink)]"><LockKeyhole size={18}/></div><div><p className="text-sm font-bold tracking-[0.16em]">PASSMANAGER</p><p className="text-[10px] uppercase tracking-[0.18em] text-[var(--muted)]">Private knowledge vault</p></div></div> }
function Nav({ icon, active, onClick, children, disabled }: { icon:ReactNode; active:boolean; onClick?:()=>void; children:ReactNode; disabled?:boolean }) { return <button disabled={disabled} onClick={onClick} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm transition ${active?'bg-[var(--mint)]/10 text-white':'text-[var(--muted)] hover:bg-white/[0.06] hover:text-white'} disabled:cursor-not-allowed disabled:opacity-40`}>{icon}{children}</button> }
function EmptyVault({ onCreate }: { onCreate:()=>void }) { return <section className="grid min-h-[450px] place-items-center rounded-3xl border border-dashed border-white/10 bg-white/[0.025] text-center"><div><ShieldCheck size={34} className="mx-auto text-[var(--mint)]"/><h2 className="mt-5 text-2xl font-semibold">Your private workspace.</h2><p className="mt-3 max-w-md text-sm leading-6 text-[var(--muted)]">创建或选择一个 vault，联系人、密码和笔记都会加密保存在其中。</p><Button className="mt-7" onClick={onCreate}><Plus size={16}/>Create vault</Button></div></section> }
function PeopleWorkspace({ people, selected, query, setQuery, onAdd, onOpen, onEdit, onDelete }: { people:PersonSummary[];selected:Person|null;query:string;setQuery:(v:string)=>void;onAdd:()=>void;onOpen:(id:string)=>void;onEdit:()=>void;onDelete:()=>void }) { return <section><div className="mb-5 flex gap-3"><SearchBox value={query} setValue={setQuery} placeholder="Search people, email, phone..."/><Button onClick={onAdd}><Plus size={16}/>New person</Button></div><div className="grid min-h-[540px] grid-cols-1 overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.025] lg:grid-cols-[minmax(280px,0.8fr)_minmax(420px,1.4fr)]"><div className="border-b border-white/[0.08] lg:border-r lg:border-b-0">{people.map(p => <button key={p.person_id} onClick={() => onOpen(p.person_id)} className={`flex w-full items-center gap-3 border-b border-white/[0.06] px-5 py-4 text-left transition hover:bg-white/[0.06] ${selected?.person_id===p.person_id?'bg-[var(--mint)]/10':''}`}><span className="grid size-9 shrink-0 place-items-center rounded-full bg-white/[0.08] text-sm font-semibold text-[var(--mint)]">{p.name.slice(0,1)}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{p.name}</strong><small className="text-xs text-[var(--muted)]">{p.gender || '未设置'} · {p.contact_count} contacts</small></span><ChevronRight size={16} className="text-[var(--muted)]"/></button>)}{people.length===0 && <p className="p-8 text-center text-sm text-[var(--muted)]">No people yet.</p>}</div><PersonDetail person={selected} onEdit={onEdit} onDelete={onDelete}/></div></section> }
function PersonDetail({ person, onEdit, onDelete }: { person:Person|null;onEdit:()=>void;onDelete:()=>void }) { if (!person) return <div className="grid place-items-center p-10 text-center text-sm text-[var(--muted)]"><div><ContactRound size={30} className="mx-auto mb-4 text-[var(--mint)]"/>选择一个联系人，查看其联系方式、备注与后续关系记录。</div></div>; return <article className="p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-[var(--mint)]/15 text-xl font-semibold text-[var(--mint)]">{person.name.slice(0,1)}</span><div className="min-w-0 flex-1"><h2 className="text-2xl font-semibold">{person.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">{person.gender || '未设置'}{person.birthday ? ` · ${person.birthday}` : ''}</p></div><Button variant="quiet" onClick={onEdit}>Edit</Button><button onClick={onDelete} className="p-2 text-[var(--muted)] transition hover:scale-110 hover:text-red-300" aria-label="删除联系人"><Trash2 size={17}/></button></div><hr className="my-7 border-white/[0.08]"/><h3 className="text-sm font-semibold">Contact methods</h3><div className="mt-3 space-y-2">{person.contacts.map(c => <div key={c.contact_id} className="flex items-center gap-3 rounded-xl bg-black/15 px-4 py-3"><ContactIcon kind={c.kind}/><div className="min-w-0"><p className="text-sm">{c.value}{c.is_primary && <span className="ml-2 text-[10px] uppercase tracking-wider text-[var(--mint)]">primary</span>}</p><p className="text-xs text-[var(--muted)]">{c.label || c.kind}</p></div></div>)}{person.contacts.length===0 && <p className="text-sm text-[var(--muted)]">No contact methods added.</p>}</div>{person.note && <><h3 className="mt-7 text-sm font-semibold">Private note</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[var(--muted)]">{person.note}</p></>}</article> }
function ContactIcon({ kind }: { kind:string }) { const value=kind.toLowerCase(); return value.includes('mail')||value.includes('email')?<Mail size={16} className="text-[var(--mint)]"/>:value.includes('phone')||value.includes('tel')?<Phone size={16} className="text-[var(--mint)]"/>:<AtSign size={16} className="text-[var(--mint)]"/> }
function CredentialsWorkspace({ credentials,query,setQuery }: { credentials:Credential[];query:string;setQuery:(v:string)=>void }) { return <section><div className="mb-5"><SearchBox value={query} setValue={setQuery} placeholder="Search credentials..."/></div><div className="grid gap-3">{credentials.map(c => <article key={c.credential_id} className="rounded-xl border border-white/[0.08] bg-white/[0.035] p-5"><KeyRound size={18} className="float-left mr-3 mt-1 text-[var(--mint)]"/><strong>{c.title}</strong><p className="mt-1 text-sm text-[var(--muted)]">{c.username || c.url || 'Private credential'}</p></article>)}{credentials.length===0 && <p className="py-16 text-center text-sm text-[var(--muted)]">Credentials remain available here; contact management is now the primary workspace.</p>}</div></section> }
function SearchBox({ value,setValue,placeholder }: { value:string;setValue:(v:string)=>void;placeholder:string }) { return <label className="flex h-12 flex-1 items-center gap-3 rounded-xl border border-white/10 bg-white/[0.045] px-4 text-[var(--muted)]"><Search size={18}/><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-white outline-none"/></label> }
function PersonDialog({ person,onCancel,onSave }: { person:Person;onCancel:()=>void;onSave:(input:PersonInput,id?:string)=>void }) { const [form,setForm]=useState<PersonInput>({name:person.name,gender:person.gender,birthday:person.birthday||'',note:person.note||'',contacts:person.contacts.map(c=>({kind:c.kind,value:c.value,label:c.label||'',is_primary:c.is_primary}))}); const update=(key:keyof PersonInput,value:string)=>setForm({...form,[key]:value}); const updateContact=(i:number,key:keyof ContactInput,value:string|boolean)=>setForm({...form,contacts:form.contacts.map((c,n)=>n===i?{...c,[key]:value}:c)}); return <Modal><form onSubmit={e=>{e.preventDefault();onSave(form,person.person_id||undefined)}}><h2 className="text-xl font-semibold">{person.person_id?'Edit person':'New person'}</h2><div className="mt-5 grid gap-3"><Field label="Name" required value={form.name} onChange={v=>update('name',v)}/><div className="grid grid-cols-2 gap-3"><Field label="Gender" value={form.gender} onChange={v=>update('gender',v)}/><Field label="Birthday" type="date" value={form.birthday} onChange={v=>update('birthday',v)}/></div><label className="block text-sm text-[var(--muted)]">Private note<textarea value={form.note} onChange={e=>update('note',e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-white"/></label><div className="pt-2"><div className="mb-2 flex items-center justify-between"><span className="text-sm text-[var(--muted)]">Contact methods</span><button type="button" onClick={()=>setForm({...form,contacts:[...form.contacts,{kind:'email',value:'',label:'',is_primary:form.contacts.length===0}]})} className="text-xs text-[var(--mint)] hover:underline">+ Add contact</button></div>{form.contacts.map((c,i)=><div key={i} className="mb-2 grid grid-cols-[100px_1fr_auto] gap-2"><input value={c.kind} onChange={e=>updateContact(i,'kind',e.target.value)} placeholder="email" className="h-10 rounded-lg border border-white/10 bg-black/20 px-2 text-sm text-white"/><input value={c.value} onChange={e=>updateContact(i,'value',e.target.value)} placeholder="value" className="h-10 rounded-lg border border-white/10 bg-black/20 px-2 text-sm text-white"/><button type="button" onClick={()=>setForm({...form,contacts:form.contacts.filter((_,n)=>n!==i)})} className="text-[var(--muted)] hover:text-red-300"><Trash2 size={16}/></button></div>)}</div></div><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="quiet" onClick={onCancel}>Cancel</Button><Button type="submit">Save encrypted</Button></div></form></Modal> }
function Field({ label,value,onChange,type='text',required=false }: { label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean }) { return <label className="block text-sm text-[var(--muted)]">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-white"/></label> }
function AuthScreen({ needsRegistration,onSuccess,notify }: { needsRegistration:boolean;onSuccess:(a:AuthState)=>void;notify:(m:string)=>void }) { const [register,setRegister]=useState(needsRegistration);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState<string|null>(null);const submit=async(e:FormEvent)=>{e.preventDefault();setError(null);try{onSuccess(await invoke<AuthState>(register?'register_account':'login',{username,password}))}catch(err){const message=String(err);setError(message);notify(message)}};return <main className="h-screen min-h-[420px] overflow-hidden bg-[var(--ink)] text-white"><TitleBar/><div className="grid h-[calc(100%-40px)] place-items-center overflow-y-auto p-5"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.045] p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--mint)]">{register?'First-time setup':'Local sign in'}</p><h1 className="mt-2 text-3xl font-semibold">{register?'Create an account.':'Welcome back.'}</h1><div className="mt-7"><Field label="Account" required value={username} onChange={setUsername}/></div><div className="mt-4"><Field label="Password" type="password" required value={password} onChange={setPassword}/></div>{error&&<p role="alert" className="mt-4 rounded-lg border border-red-400/30 bg-red-400/10 px-3 py-2 text-sm text-red-200">{error}</p>}<Button type="submit" className="mt-7 w-full">{register?'Register locally':'Sign in'}</Button><button type="button" onClick={()=>{setRegister(v=>!v);setError(null)}} className="mt-5 w-full text-xs text-[var(--muted)]">{register?'Already have an account? Sign in':'Need a local account? Register'}</button></form></div></main> }
function UnlockDialog({ vault,password,setPassword,onCancel,onSubmit }: { vault:string;password:string;setPassword:(v:string)=>void;onCancel:()=>void;onSubmit:(e:FormEvent)=>void }) { return <Modal><form onSubmit={onSubmit}><h2 className="text-xl font-semibold">Unlock {vault}</h2><p className="mt-2 text-sm text-[var(--muted)]">主密码只用于解锁本次内存会话。</p><input autoFocus required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-5 h-11 w-full rounded-lg border border-white/10 bg-black/20 px-3 text-white"/><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="quiet" onClick={onCancel}>Cancel</Button><Button type="submit"><Unlock size={16}/>Unlock</Button></div></form></Modal> }
function CreateVaultDialog({ onCancel,onCreated,notify }: { onCancel:()=>void;onCreated:(id:string)=>void;notify:(m:string)=>void }) { const [id,setId]=useState('');const [password,setPassword]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await invoke('create_vault',{vaultId:id,masterPassword:password});onCreated(id);notify('Vault 已创建。')}catch(err){notify(String(err))}};return <Modal><form onSubmit={submit}><h2 className="text-xl font-semibold">Create vault</h2><Field label="Vault ID" required value={id} onChange={setId}/><div className="mt-3"><Field label="Master password" required type="password" value={password} onChange={setPassword}/></div><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="quiet" onClick={onCancel}>Cancel</Button><Button type="submit"><Plus size={16}/>Create</Button></div></form></Modal> }
function Modal({children}:{children:ReactNode}) { return <div className="fixed inset-0 z-30 grid place-items-center bg-black/70 p-5"><div className="w-full max-w-xl rounded-2xl border border-white/10 bg-[#17221f] p-6 shadow-2xl">{children}</div></div> }
export default App
